/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "errno.h"
#include "rpc/rpc.h"
#include "rpc.h"
#include "stdio.h"
#include "stdlib.h"
#include "math.h"

	CLIENT *cl;
	CLIENT *cl2;
	proy_in in;
	proy_in2 in2;
	char user[256];
	char pass[256];
	rta *tok;
	rta *tok2;
void ingreso()
{
	
	printf ("Escriba el usuario ");
  	scanf("%s",(in.usuario)); 

  	printf ("Escriba la contraseña ");
  	scanf("%s",(in.pass));     
  	printf ("tu usuario es : %s y la contraseña es %s \n",(in.usuario),(in.pass));


	if((tok=login_1(&in,cl))==NULL)
	{
		printf("\nerror :%s",clnt_sperror(cl,argv[1]));
		exit(-1);
	}
	if(tok->rta==0)
	{
		printf("usuario o contraseña invalido\n");
		exit(1);
	}
	else
	{
		printf("bienvenido amigo \n");
	}
		printf("el token es %d\n",tok->rta);
		
	 inicio();


}
void inicio()
{
	for(;;){
	char salida[30];
	scanf("%s",salida);

		if(strmp(salida,"salir"))
		{
			cerrar();
		}
	}

}
void cerrar()
{
		printf("%s \n",in.usuario);
		strcpy(in2.usuario,in.usuario);
		in2.token=tok->rta;

		if((tok2=logout_1(&in2,cl))==NULL)
		{
			printf("\nerror :%s",clnt_sperror(cl,argv[1]));
			exit(-1);
		}
		printf("%d\n", tok2->rta);
		printf("bien ... \n");
		system.exit(0);
}


int main (int argc, char **argv)
{

  	
  	if(argc!=2)
  	{
  		printf("\n argumentos insuficientes");
  		exit(-1);
  	}
  	cl=clnt_create(argv[1],PROY_PROG,PROY_VERS,"tcp");
  	if(cl==NULL)
  	{
  		printf("\n error %s",strerror(errno));
  		exit(-1);
  	}

  	ingreso();

	}