/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct proy_in {
	char *usuario;
	char *pass;
};
typedef struct proy_in proy_in;

struct proy_in2 {
	char *usuario;
	int token;
};
typedef struct proy_in2 proy_in2;

struct proy_out {
	int token;
};
typedef struct proy_out proy_out;

#define PROY_PROG 0x31540000
#define PROY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PROYPROC 1
extern  proy_out * proyproc_1(proy_in *, CLIENT *);
extern  proy_out * proyproc_1_svc(proy_in *, struct svc_req *);
extern int proy_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PROYPROC 1
extern  proy_out * proyproc_1();
extern  proy_out * proyproc_1_svc();
extern int proy_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_proy_in (XDR *, proy_in*);
extern  bool_t xdr_proy_in2 (XDR *, proy_in2*);
extern  bool_t xdr_proy_out (XDR *, proy_out*);

#else /* K&R C */
extern bool_t xdr_proy_in ();
extern bool_t xdr_proy_in2 ();
extern bool_t xdr_proy_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
