/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"

proy_out *
proyproc_1_svc(proy_in *argp, struct svc_req *rqstp)
{
	static proy_out  result;

	/*
	 * insert server code here
	 */

	return &result;
}
