/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_proy_in (XDR *xdrs, proy_in *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->usuario, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->pass, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_proy_in2 (XDR *xdrs, proy_in2 *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->usuario, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_proy_out (XDR *xdrs, proy_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->token))
		 return FALSE;
	return TRUE;
}
