/*
* This is sample code generated by rpcgen.
* These are only templates and you can use them
* as a guideline for developing your own functions.
*/
#include "rpc.h"
#include "string.h"
#include "assert.h"
#include "stdio.h"
#include "stdlib.h"
char ** str_split(char * a_str,const char a_delim)
{
	char ** result =0;
	size_t count =0;
	char * last_comma =0;
	char *tmp =a_str;
	char delim[2];
	delim[0]=a_delim;
	delim[1]=0;
	while(*tmp)
	{
		if(a_delim==*tmp)
		{
			count++;
			last_comma = tmp;
		}
		tmp++;
	}
	count += last_comma<(a_str + strlen(a_str)-1);
	count ++;
	result=malloc(sizeof(char*)* count);
	if(result)
	{
		size_t idx = 0;
		char* token = strtok(a_str,delim);
		while(token)
		{
			assert(idx < count);
			*(result + idx++) = strdup(token);
			token = strtok(0,delim);
		}
		assert(idx==count-1);
		*(result + idx)=0;
	}
	return result;
}
rta * login_1_svc(proy_in *in, struct svc_req *rqstp)
{
	char buffer[1000];
	FILE *fp;
	fp=fopen ("users.txt","r");
	fscanf(fp,"%s",buffer);
	char **tokens;
	char **user;
	int desicion=0;
	tokens= str_split(buffer,',');
	if(tokens)
	{
		int i;
		for(i=0;*(tokens+i);i++)
		{
			user=str_split(*(tokens+i),'-');
			if(strcmp(in->usuario,user[0])==0)
			{
				if(strcmp(in->pass,user[1])==0)
				{
					desicion=1;
				}
			}
		}
	}
	static rta result;
	if(desicion==1)
	{
		result.rta=rand()%1000+1;
	}
	else
	{
		result.rta=0;
	}
	fclose(fp);
	if(result.rta!=0)
	{
		char buffer[sizeof(result.rta)];
		snprintf(buffer,sizeof(buffer),"%d",result.rta);
		FILE *fp;
		fp=fopen(in->usuario,"w");
		fputs(buffer,fp);
		fclose(fp);
	}
	return &result;
}
rta *
logout_1_svc(proy_in2 *in2, struct svc_req *rqstp)
{
	static rta result;
	printf("hola \n");
	char leer[10];
	FILE *fp;
	fp=fopen(in2->usuario,"r");
	fscanf(fp,"%s",leer);
	char token[sizeof(in2->token)];
	result.rta=2;
	snprintf(token,sizeof(token),"%d",in2->token);
	printf("%d \n",in2->token );
	if(strcmp(token,leer)==0)
	{
		result.rta=0;
	}
	else{
		result.rta=1;
	}
	fclose(fp);
	remove(in2->usuario);
	return &result;
}