/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_proy_in (XDR *xdrs, proy_in *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->usuario, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->pass, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_proy_in2 (XDR *xdrs, proy_in2 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->usuario, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rta (XDR *xdrs, rta *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->rta))
		 return FALSE;
	return TRUE;
}
